#!/usr/bin/env python3
"""Generate / refresh ARCH.md — a deterministic, no-truncation file-tree map.

Design notes
------------
* File set comes from `git ls-files --cached --others --exclude-standard`, which
  respects `.gitignore` for BOTH blocklist and allowlist (`*` then `!path`) repos
  and is fully deterministic. (`tree --gitignore` silently empties allowlist repos.)
* Only the block between the ARCH:TREE markers is regenerated. The "## Overview"
  prose and the "## Key Paths" (ARCH:DESC) block are CURATED zones — preserved
  verbatim across runs. Populate them with the code-explorer agent.
* Inline one-line descriptions are sourced from the Key Paths block and injected
  next to matching tree entries on every regeneration, so they never go stale or
  get wiped.

Usage:
    gen_arch.py [--root DIR] [--quiet] [--check | --check-tooling]

  --check         : exit 1 if ARCH.md is out of date (CI guard); makes no changes.
  --check-tooling : warn (never fail) if THIS copy is out of sync with the
                    canonical template. See __version__ below.
"""

from __future__ import annotations

import argparse
import os
import re
import subprocess
import sys
from pathlib import Path

# Bump on every behaviour change. This exists because the script is DISTRIBUTED BY
# COPY: install-arch-map.sh does an unconditional `cp` into each repo's .githooks/,
# after which every copy is an independent tracked file with no upstream link.
#
# That gap has already bitten twice. The sibling `pre-commit` fragmented into three
# versions — the 2026-07-29 silent-`exit 1` fix landed in the template and was never
# delivered to BotHaus / TradingBots / VistaMobileBE, which still run the buggy copy.
# And the ARCH.md footer conflict (see FOOTER below) had to be fixed in four repos
# by hand. Nothing detected either, because there was no version to compare and
# `--check` only validates the OUTPUT (ARCH.md) — never the tooling that made it.
#
# `--check-tooling` closes that: the pre-commit hook compares the installed copy
# against the canonical template and warns on a mismatch.
__version__ = "2.0.0"

# Where the canonical template lives. Overridable so a different machine layout or
# a test can point elsewhere; absent → the check silently no-ops (CI, collaborators,
# any box without this user's ~/.claude checkout).
CANONICAL_ENV = "ARCH_MAP_CANONICAL"
CANONICAL_DEFAULT = Path.home() / ".claude" / "scripts" / "arch-map" / "gen_arch.py"

VERSION_RE = re.compile(r"^__version__\s*=\s*[\"']([0-9]+(?:\.[0-9]+)*)[\"']", re.M)

TREE_START = "<!-- ARCH:TREE:START — generated by gen_arch.py; do not edit inside, do not remove -->"
TREE_END = "<!-- ARCH:TREE:END -->"
DESC_START = (
    "<!-- ARCH:DESC:START — curated; one line per key path, preserved across regens -->"
)
DESC_END = "<!-- ARCH:DESC:END -->"

# `- `path`` or `- `dir/`` followed by an em-dash / hyphen and a description.
DESC_LINE = re.compile(r"^- +`([^`]+)` +[—–-] +(.+?)\s*$")

# The footer deliberately carries NO volatile or global state.
#
# It used to read `_Generated <timestamp> · <N> files · <M> directories._`. Both
# halves are per-branch global state on a single line, which made ARCH.md conflict
# *by construction*: any two branches whose file counts differ rewrite that line
# differently, so every branch conflicts with main on it regardless of where in the
# tree it actually added files. That stalled VistaMobileBE PRs #54, #84 and #122 for
# 10 days — in #84 it was the ONLY conflicting hunk across 65 commits of divergence.
#
# Verified: two branches adding 3 and 1 files in distant directories conflict on the
# footer alone. Their TIMESTAMPS matched (same minute), so the file COUNT by itself
# is sufficient — dropping only the timestamp would not have fixed it.
#
# Do NOT "fix" this with a `.gitattributes merge=<driver>`. Tried and rejected: a
# regenerating driver silently LOSES FILES, because drivers run mid-merge before the
# index is final, so `git ls-files --cached` cannot see the other side's new paths;
# an auto-resolved merge then never fires pre-commit to correct it. `-X ours`/
# `-X theirs` fail the same way — for a generated file neither side is right, since
# each holds a correct tree for its own file set and the merge needs the union.
# Drivers also live in local `git config`, so GitHub's server-side conflict
# detection never runs them and a conflicted PR stays blocked regardless.
#
# Residual same-tree-region conflicts are genuine. Resolve by regenerating:
#   git checkout --ours -- ARCH.md && python3 .githooks/gen_arch.py
#
# What the stamp provided is already in git: `git log -1 -- ARCH.md`.
FOOTER = (
    "_Generated by `.githooks/gen_arch.py` — do not edit inside the ARCH:TREE markers._"
)

# NOTE: there is deliberately no normalize()/STAMP_RE shim any more.
#
# The old one existed because the footer held a timestamp: without normalizing it
# away, every run rewrote ARCH.md and churned the working tree. With a static footer
# the generator is fully deterministic, so plain equality is the correct staleness
# test and no shim is needed.
#
# A first draft of this change kept a shim mapping the LEGACY timestamped footer onto
# FOOTER, reasoning that it would stop `--check` reporting a spurious stale on the
# transitional commit. That was wrong twice over, and it silently defeated the fix:
#   1. During the transition the file genuinely IS out of date — saying so is correct,
#      not spurious.
#   2. Because the shim made old and new compare EQUAL, `changed` stayed False and the
#      footer was never rewritten. Observed live: after regenerating, ARCH.md still
#      carried `_Generated <timestamp> · 359 files · 87 directories._`.
# It only appeared to work in the repo where it was first tried, because the file tree
# happened to change in the same commit and dragged the whole tree block along with it.
# Swapping a file for a symlink at the same path — or editing only .githooks/ — changes
# no tree entry, so nothing would have triggered the rewrite.


def _parse_version(text: str) -> tuple[int, ...] | None:
    m = VERSION_RE.search(text)
    return tuple(int(p) for p in m.group(1).split(".")) if m else None


def check_tooling(quiet: bool = False) -> int:
    """Warn if this copy is out of sync with the canonical template.

    Always returns 0 — this is a warning, never a gate. A stale generator still
    produces a usable ARCH.md; blocking the commit would be a worse trade than
    printing a notice. Reads the canonical file as TEXT and regexes out its
    version rather than importing it, so a broken template cannot execute here.
    """
    canonical = Path(os.environ.get(CANONICAL_ENV, CANONICAL_DEFAULT)).expanduser()
    mine = _parse_version(Path(__file__).read_text(encoding="utf-8"))

    if not canonical.is_file():
        return 0  # no canonical on this box (CI, collaborator) → nothing to compare
    try:
        if canonical.resolve() == Path(__file__).resolve():
            return 0  # this IS the canonical (or a symlink to it) → always in sync
    except OSError:
        return 0

    theirs = _parse_version(canonical.read_text(encoding="utf-8"))
    if mine is None or theirs is None or mine == theirs:
        return 0

    if not quiet:
        rel = f"{canonical}"
        if mine < theirs:
            print(
                f"arch-map: this repo's gen_arch.py is v{'.'.join(map(str, mine))}, "
                f"canonical is v{'.'.join(map(str, theirs))} — installed copy is STALE.\n"
                f"          Refresh:  cp {rel} .githooks/gen_arch.py\n"
                f"          (copy gen_arch.py ALONE — install-arch-map.sh would also "
                f"overwrite .githooks/pre-commit.)",
                file=sys.stderr,
            )
        else:
            print(
                f"arch-map: this repo's gen_arch.py is v{'.'.join(map(str, mine))}, "
                f"AHEAD of canonical v{'.'.join(map(str, theirs))} — edited in-repo.\n"
                f"          Port the change back to {rel} or the next sweep reverts it.",
                file=sys.stderr,
            )
    return 0


def sh(args: list[str], cwd: Path) -> str:
    return subprocess.run(
        args, cwd=cwd, check=True, capture_output=True, text=True
    ).stdout


def list_paths(root: Path) -> list[str]:
    """Tracked + untracked-but-not-ignored files, .gitignore-respecting."""
    out = sh(
        ["git", "ls-files", "--cached", "--others", "--exclude-standard", "-z"],
        root,
    )
    paths = [p for p in out.split("\0") if p]
    return sorted(set(paths))


# --------------------------------------------------------------------------- #
# Tree model
# --------------------------------------------------------------------------- #
class Node:
    __slots__ = ("name", "children", "is_dir")

    def __init__(self, name: str, is_dir: bool):
        self.name = name
        self.is_dir = is_dir
        self.children: dict[str, "Node"] = {}


def build_tree(paths: list[str]) -> Node:
    root = Node("", True)
    for p in paths:
        parts = p.split("/")
        cur = root
        for i, part in enumerate(parts):
            is_dir = i < len(parts) - 1
            child = cur.children.get(part)
            if child is None:
                child = Node(part, is_dir)
                cur.children[part] = child
            # a path component that later turns out to be a parent is a dir
            if is_dir:
                child.is_dir = True
            cur = child
    return root


def sorted_children(node: Node) -> list[Node]:
    # directories first, then files; each alphabetical (case-insensitive)
    return sorted(
        node.children.values(),
        key=lambda n: (not n.is_dir, n.name.lower()),
    )


def render(node: Node, descs: dict[str, str]) -> tuple[list[str], int, int]:
    """Return (lines, n_files, n_dirs). Root's own name is not printed."""
    lines: list[str] = []
    counts = {"files": 0, "dirs": 0}

    def walk(n: Node, prefix: str, path: str):
        kids = sorted_children(n)
        for i, child in enumerate(kids):
            last = i == len(kids) - 1
            connector = "└── " if last else "├── "
            child_path = f"{path}{child.name}"
            label = child.name + ("/" if child.is_dir else "")
            key = child_path + ("/" if child.is_dir else "")
            desc = descs.get(key) or descs.get(child_path)
            suffix = f"  — {desc}" if desc else ""
            lines.append(f"{prefix}{connector}{label}{suffix}")
            if child.is_dir:
                counts["dirs"] += 1
                ext = "    " if last else "│   "
                walk(child, prefix + ext, child_path + "/")
            else:
                counts["files"] += 1

    walk(node, "", "")
    return lines, counts["files"], counts["dirs"]


# --------------------------------------------------------------------------- #
# ARCH.md assembly (preserve curated zones)
# --------------------------------------------------------------------------- #
def parse_descs(text: str) -> dict[str, str]:
    descs: dict[str, str] = {}
    if DESC_START not in text:
        return descs
    block = text.split(DESC_START, 1)[1].split(DESC_END, 1)[0]
    for line in block.splitlines():
        m = DESC_LINE.match(line)
        if m:
            key, desc = m.group(1).strip(), m.group(2).strip()
            if desc and desc.upper() != "TODO":
                descs[key] = desc
    return descs


def default_scaffold(repo: str, top_level: list[Node]) -> str:
    seed = "\n".join(f"- `{n.name}{'/' if n.is_dir else ''}` — TODO" for n in top_level)
    return (
        f"# Architecture Map — {repo}\n\n"
        "> **Auto-maintained.** The file tree below (between the `ARCH:TREE` markers) is "
        "regenerated on every commit by `.githooks/pre-commit` and can be refreshed manually "
        "with `python3 .githooks/gen_arch.py`. The **Overview** and **Key Paths** sections are "
        "curated (fill them with the `code-explorer` agent); they are preserved across "
        "regenerations. Descriptions in *Key Paths* are injected inline into the tree.\n\n"
        "## Overview\n\n"
        "_Replace this with a short architectural overview (entry points, layers, data flow). "
        "Run the `code-explorer` agent to populate it._\n\n"
        "## Key Paths\n\n"
        f"{DESC_START}\n{seed}\n{DESC_END}\n\n"
        "## File Tree\n\n"
    )


def repo_label(root: Path) -> str:
    """Stable tree-root label for ARCH.md.

    Order matters:

    1. The `origin` remote URL basename. Survives a checkout whose directory
       name differs from the repo name — ClaudeConfig lives at `~/.claude`,
       so a path-derived label reads `.claude`.
    2. The main worktree's basename. A linked worktree's own folder name
       (`.worktrees/feat-foo`) must never leak into the label, or every
       branch produces a different root and PRs conflict on it.
    3. `root.name`, if this is not a git repo at all.
    """
    try:
        url = sh(["git", "remote", "get-url", "origin"], root).strip()
        if url:
            # Strip a trailing `.git`, then take the last path segment. The
            # second split handles SCP-style SSH (`git@host:owner/repo.git`),
            # where the host/path separator is `:` rather than `/`.
            name = re.sub(r"\.git$", "", url.rstrip("/"))
            name = name.rsplit("/", 1)[-1].rsplit(":", 1)[-1]
            if name:
                return name
    except subprocess.CalledProcessError:
        pass  # no remote configured — fall through
    try:
        common = sh(["git", "rev-parse", "--git-common-dir"], root).strip()
        return (root / common).resolve().parent.name
    except subprocess.CalledProcessError:
        return root.name


def build_document(root: Path, existing: str | None) -> str:
    repo = repo_label(root)
    paths = list_paths(root)
    tree = build_tree(paths)
    descs = parse_descs(existing or "")
    lines, _n_files, _n_dirs = render(tree, descs)

    tree_block = (
        f"{TREE_START}\n```\n{repo}/\n"
        + ("\n".join(lines) + "\n" if lines else "")
        + "```\n"
        + f"\n{FOOTER}\n"
        + f"{TREE_END}\n"
    )

    if existing and TREE_START in existing and TREE_END in existing:
        prefix = existing.split(TREE_START, 1)[0]
        suffix = existing.split(TREE_END, 1)[1]
        doc = prefix + tree_block + suffix
    else:
        doc = default_scaffold(repo, sorted_children(tree)) + tree_block
    # exactly one trailing newline → idempotent (no blank-line growth across runs)
    return doc.rstrip("\n") + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description="Generate/refresh ARCH.md")
    ap.add_argument("--root", default=None, help="repo root (default: git toplevel)")
    ap.add_argument("--quiet", action="store_true")
    ap.add_argument("--check", action="store_true", help="exit 1 if stale; no write")
    ap.add_argument(
        "--check-tooling",
        action="store_true",
        help="warn (never fail) if this copy is out of sync with the canonical template",
    )
    ap.add_argument("--version", action="version", version=f"gen_arch.py {__version__}")
    args = ap.parse_args()

    # Deliberately before the repo lookup: the tooling check is about THIS FILE, not
    # about any repo, so it must work from anywhere (and not exit 2 outside a repo).
    if args.check_tooling:
        return check_tooling(quiet=args.quiet)

    if args.root:
        root = Path(args.root).resolve()
    else:
        try:
            root = Path(sh(["git", "rev-parse", "--show-toplevel"], Path.cwd()).strip())
        except subprocess.CalledProcessError:
            print("gen_arch: not inside a git repository", file=sys.stderr)
            return 2

    arch = root / "ARCH.md"
    existing = arch.read_text(encoding="utf-8") if arch.exists() else None
    new_doc = build_document(root, existing)

    # Plain equality: the generator is deterministic (sorted `git ls-files`, static
    # footer), so any textual difference is a real one. See the NOTE above on why the
    # old normalize() shim was removed rather than retargeted.
    changed = existing is None or existing != new_doc

    if args.check:
        if changed:
            print(f"gen_arch: {arch} is OUT OF DATE — run gen_arch.py", file=sys.stderr)
            return 1
        if not args.quiet:
            print(f"gen_arch: {arch} up to date")
        return 0

    if not changed:
        if not args.quiet:
            print(f"gen_arch: {arch} unchanged")
        return 0

    tmp = arch.with_suffix(".md.tmp")
    tmp.write_text(new_doc, encoding="utf-8")
    tmp.replace(arch)
    if not args.quiet:
        print(f"gen_arch: wrote {arch}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
